### ISSUE TITLE
rake task for one locale pack

### ISSUE THREAD

**Issue by klyrr** [corthmann/locale_pack#5]
I want to use the `rake locale_pack:compile:one[generic]` to only compile one of the locale packs we have.

But when I run it I get the following error message:

```bash
$ bundle exec rake locale_pack:compile:one['generic']
rake aborted!
ArgumentError: Locale Pack with name 'generic' not found
/Users/tina/.rvm/gems/ruby-2.4.5/bundler/gems/locale_pack-cbd5cfad0874/lib/locale_pack/models/pack_file.rb:16:in `find_by_name'
/Users/tina/.rvm/gems/ruby-2.4.5/bundler/gems/locale_pack-cbd5cfad0874/lib/locale_pack/tasks/locale_pack.rake:25:in `block (3 levels) in <top (required)>'
/Users/tina/.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/tina/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
/Users/tina/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => locale_pack:compile:one
```

Am I using the rake task not correctly? I am pretty sure there is a package with that name. I also tried `$ bundle exec rake locale_pack:compile:one['generic_en']` but with the same result.

Thanks for your help :)

**Comment by corthmann** [comment]
@klyrr Thank you for reporting this issue! :heart: 

I've made a fix for the issue. You can see the details in the PR mentioned above.
